### PR TITLE
updated README.md

### PR DESCRIPTION
**Pull request by saarques**
readme.md updated according to the use of patterns and their importance.

### CODE REVIEW

**Review by naveenyadav15 — CHANGES_REQUESTED** [review]
I want to know what is wrong with file "62.cpp".

**Comment by saarques** [comment]
Actually this 62.cpp file is a duplicate of 60.cpp file.
That's why I removed it.

**Comment by saarques** [comment]
I have added some missing patterns, you can merge them
Deleted files were duplicates:)

**Comment by naveenyadav15** [comment]
@saarques Thanks, for your contribution. And maybe we will see you in future.

**Pull request merged**
